#!/usr/bin/env ruby

puts "Hello World!"

puts "Hello, what's your name?"
name = gets
puts CheerGenerator.for(name)
puts "Hey #{name}, what's your birthday (mm/dd)?"
birthday = gets
birthdate = BirthdayParser.parse(birthday)
puts CheerGenerator.birthday(birthday)
