#!/usr/bin/env ruby

require_relative 'lib/cheer'

puts "Hello, what's your name?"
name = gets.chomp

puts Cheer.for_person(name)
puts "Hey #{name}, what's your birthday (mm/dd)?"

birthday = gets
puts Cheer.for_birthday(birthday)
